@Access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZDM1OWQyNy1jMmRmLTQ4ZDYtOWYxNC05ZmVjZTM0N2IzMDEiLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc5MDc1OTY3MSwiZXhwIjoxNzkwNzYwNTcxfQ.2dARKQuJR3qXiw8Jfyy8B7058iU0SgrKxyJxy9mzHLE
@Refresh_Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZDM1OWQyNy1jMmRmLTQ4ZDYtOWYxNC05ZmVjZTM0N2IzMDEiLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc5MDc1OTY3MSwiZXhwIjoxNzkxMzY0NDcxfQ.eyioc2T9rjJFvgjQi8IajUFrgLTQhT5cQ6f844hfuwQ

### Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "mi@leaf.test",
  "password": "Password7810@@"
}

### Guard test
POST http://localhost:3000/api/v1/auth/users/me
Authorization: Bearer {{Access_token}}

### Refresh Access Token

POST http://localhost:3000/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{Refresh_Token}}"
}
